// Code generated by mockery v2.52.2. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Buyer is an autogenerated mock type for the Buyer type
type Buyer struct {
	mock.Mock
}

// BuyItem provides a mock function with given fields: itemName, userId
func (_m *Buyer) BuyItem(itemName string, userId int) error {
	ret := _m.Called(itemName, userId)

	if len(ret) == 0 {
		panic("no return value specified for BuyItem")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, int) error); ok {
		r0 = rf(itemName, userId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CheckPassword provides a mock function with given fields: username, passwordHash
func (_m *Buyer) CheckPassword(username string, passwordHash string) (int, error) {
	ret := _m.Called(username, passwordHash)

	if len(ret) == 0 {
		panic("no return value specified for CheckPassword")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (int, error)); ok {
		return rf(username, passwordHash)
	}
	if rf, ok := ret.Get(0).(func(string, string) int); ok {
		r0 = rf(username, passwordHash)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(username, passwordHash)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewBuyer creates a new instance of Buyer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBuyer(t interface {
	mock.TestingT
	Cleanup(func())
}) *Buyer {
	mock := &Buyer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
