// Code generated by mockery v2.52.2. DO NOT EDIT.

package mocks

import (
	pair "github.com/l-golofastov/Merch-Shop-Api/internal/lib/datatype/pair"
	mock "github.com/stretchr/testify/mock"
)

// InfoHandler is an autogenerated mock type for the InfoHandler type
type InfoHandler struct {
	mock.Mock
}

// CheckPassword provides a mock function with given fields: username, passwordHash
func (_m *InfoHandler) CheckPassword(username string, passwordHash string) (int, error) {
	ret := _m.Called(username, passwordHash)

	if len(ret) == 0 {
		panic("no return value specified for CheckPassword")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (int, error)); ok {
		return rf(username, passwordHash)
	}
	if rf, ok := ret.Get(0).(func(string, string) int); ok {
		r0 = rf(username, passwordHash)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(username, passwordHash)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserCoins provides a mock function with given fields: id
func (_m *InfoHandler) GetUserCoins(id int) (int, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetUserCoins")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (int, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int) int); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserPurchases provides a mock function with given fields: id
func (_m *InfoHandler) GetUserPurchases(id int) (map[string]int, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetUserPurchases")
	}

	var r0 map[string]int
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (map[string]int, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int) map[string]int); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]int)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserReceivedCoins provides a mock function with given fields: id
func (_m *InfoHandler) GetUserReceivedCoins(id int) ([]pair.Pair[string, int], error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetUserReceivedCoins")
	}

	var r0 []pair.Pair[string, int]
	var r1 error
	if rf, ok := ret.Get(0).(func(int) ([]pair.Pair[string, int], error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int) []pair.Pair[string, int]); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]pair.Pair[string, int])
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserSentCoins provides a mock function with given fields: id
func (_m *InfoHandler) GetUserSentCoins(id int) ([]pair.Pair[string, int], error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetUserSentCoins")
	}

	var r0 []pair.Pair[string, int]
	var r1 error
	if rf, ok := ret.Get(0).(func(int) ([]pair.Pair[string, int], error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int) []pair.Pair[string, int]); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]pair.Pair[string, int])
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewInfoHandler creates a new instance of InfoHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewInfoHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *InfoHandler {
	mock := &InfoHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
