// Code generated by mockery v2.52.2. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// CoinSender is an autogenerated mock type for the CoinSender type
type CoinSender struct {
	mock.Mock
}

// CheckPassword provides a mock function with given fields: username, passwordHash
func (_m *CoinSender) CheckPassword(username string, passwordHash string) (int, error) {
	ret := _m.Called(username, passwordHash)

	if len(ret) == 0 {
		panic("no return value specified for CheckPassword")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (int, error)); ok {
		return rf(username, passwordHash)
	}
	if rf, ok := ret.Get(0).(func(string, string) int); ok {
		r0 = rf(username, passwordHash)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(username, passwordHash)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SendCoins provides a mock function with given fields: username, id, amount
func (_m *CoinSender) SendCoins(username string, id int, amount int) error {
	ret := _m.Called(username, id, amount)

	if len(ret) == 0 {
		panic("no return value specified for SendCoins")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, int, int) error); ok {
		r0 = rf(username, id, amount)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewCoinSender creates a new instance of CoinSender. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCoinSender(t interface {
	mock.TestingT
	Cleanup(func())
}) *CoinSender {
	mock := &CoinSender{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
